# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import mamushi_pb2 as mamushi__pb2


class MamushiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PushMsg = channel.unary_unary(
                '/pycli_goser.Mamushi/PushMsg',
                request_serializer=mamushi__pb2.MsgStruct.SerializeToString,
                response_deserializer=mamushi__pb2.MsgStruct.FromString,
                )


class MamushiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PushMsg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MamushiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PushMsg': grpc.unary_unary_rpc_method_handler(
                    servicer.PushMsg,
                    request_deserializer=mamushi__pb2.MsgStruct.FromString,
                    response_serializer=mamushi__pb2.MsgStruct.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pycli_goser.Mamushi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Mamushi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PushMsg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pycli_goser.Mamushi/PushMsg',
            mamushi__pb2.MsgStruct.SerializeToString,
            mamushi__pb2.MsgStruct.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
