# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mamushi.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mamushi.proto',
  package='pycli_goser',
  syntax='proto3',
  serialized_options=b'Z\001/',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rmamushi.proto\x12\x0bpycli_goser\"\x1c\n\tMsgStruct\x12\x0f\n\x07message\x18\x01 \x01(\t2F\n\x07Mamushi\x12;\n\x07PushMsg\x12\x16.pycli_goser.MsgStruct\x1a\x16.pycli_goser.MsgStruct\"\x00\x42\x03Z\x01/b\x06proto3'
)




_MSGSTRUCT = _descriptor.Descriptor(
  name='MsgStruct',
  full_name='pycli_goser.MsgStruct',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='pycli_goser.MsgStruct.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=58,
)

DESCRIPTOR.message_types_by_name['MsgStruct'] = _MSGSTRUCT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MsgStruct = _reflection.GeneratedProtocolMessageType('MsgStruct', (_message.Message,), {
  'DESCRIPTOR' : _MSGSTRUCT,
  '__module__' : 'mamushi_pb2'
  # @@protoc_insertion_point(class_scope:pycli_goser.MsgStruct)
  })
_sym_db.RegisterMessage(MsgStruct)


DESCRIPTOR._options = None

_MAMUSHI = _descriptor.ServiceDescriptor(
  name='Mamushi',
  full_name='pycli_goser.Mamushi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=60,
  serialized_end=130,
  methods=[
  _descriptor.MethodDescriptor(
    name='PushMsg',
    full_name='pycli_goser.Mamushi.PushMsg',
    index=0,
    containing_service=None,
    input_type=_MSGSTRUCT,
    output_type=_MSGSTRUCT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MAMUSHI)

DESCRIPTOR.services_by_name['Mamushi'] = _MAMUSHI

# @@protoc_insertion_point(module_scope)
